### ISSUE TITLE
Error WMS dataset loading

### ISSUE THREAD

**Issue by Gpetrak** [GeoNode/QGISGeoNodePlugin#279] opened 2024-10-31 14:58 UTC
This error is observed when the user tries to load a dataset through WMS, in order to display it on the QGIS canvas: 

```bash
Unable to load layer 10.1 buffer: Provider is not valid (provider: wms, URI: crs=EPSG:4326&url=https://stable.demo.geonode.org/geoserver/ows&format=image/png&layers=geonode:101_15kmf&styles=&version=auto
```
During the loading process, the plugin creates the task object using the LayerLoaderTask class but during the run() method execution, the qgis.core.QgsRasterLayer returns an invalid layer through the _load_wms() method. 
As a result when the task processing starts, it fails with a result == False in the network.NetworkRequestTask.finished() method.

Regarding QGIS responses, it seems to fail in the GetCapabilities request:
![Screenshot from 2024-10-31 16-31-58](https://github.com/user-attachments/assets/d6d66e98-e646-41a7-bc47-9901b9cfc386)

I deleted the cache (including the network authentication cache) but the error remains the same.

I'ts worth noting that this issue was observed only in the GeoNode Stable demo instance which includes thousands of layers.

**Comment by giohappy** [comment] 2024-10-31 16:12
Maybe a timeout of the event loop executing the request inside the network task @Gpetrak? 
Have you tried using the WMS service from stable demo directly through QGIS WMS provider? 

Please go on investigating the problem.

**Comment by Gpetrak** [comment] 2024-11-01 08:34
@giohappy indeed, the core WMS service provider also fails with the same QGIS response (`operation canceled` in WMS GetCapablilities`) while the QGIS logs denote a timeout error:
```bash
Network request https://stable.demo.geonode.org/geoserver/wms?SERVICE=WMS&REQUEST=GetCapabilities timed out
```
 So, I suppose that the issue doesn't come from the plugin but from QGIS. Maybe we have to open an issue for this in QGIS ?
I searched for other large WMS servers in order to test it but I couldn't find such large :-)

**Comment by giohappy** [comment] 2024-11-13 17:51
@Gpetrak I wasn't able to reproduce this error, except there are problems with the stable demo because of the huge GetCapabilities document.
I will close this. It can be reopened if it happens again and it can be reproduced also for other scenarios.

**Closed by giohappy** 2024-11-13 17:51 UTC
Labels: type: bug
